import { RealtimeAgent, RealtimeSession } from "@openai/agents/realtime";

/**
 * Creates and connects a new OpenAI Realtime Session using an Ephemeral Token 
 * generated by our secure SvelteKit backend route.
 */
export async function createCookingSession() {
    // Request microphone access
    try {
        await navigator.mediaDevices.getUserMedia({ audio: true });
    } catch {
        throw new Error("Microphone access denied.");
    }

    // Fetch ephemeral token from backend
    console.log(">>> Fetching token from /api/realtime-session");
    const response = await fetch('/api/realtime-session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
    });
    
    if (!response.ok) {
        const text = await response.text();
        console.error(">>> Server error:", response.status, text);
        throw new Error('Failed to fetch ephemeral token from server');
    }
    
    const sessionData = await response.json();
    console.log(">>> Server response object:", sessionData);
    console.log(">>> Response keys:", Object.keys(sessionData));
    console.log(">>> client_secret:", sessionData.client_secret);
    
    const clientApiKey = sessionData.client_secret?.value;
    console.log(">>> Extracted ephemeral token:", clientApiKey ? "✅" : "❌");
    
    if (!clientApiKey) {
        console.error(">>> PROBLEM: client_secret.value not found!");
        throw new Error('Server did not return ephemeral token');
    }

    // Official OpenAI code
    const agent = new RealtimeAgent({
        name: "Assistant",
        instructions: "You are a helpful assistant.",
    });

    const session = new RealtimeSession(agent);

    console.log(">>> Connecting via secure Ephemeral Token...");
    try {
        await session.connect({
            model: sessionData.model,
            apiKey: clientApiKey,
        });
        console.log(">>> SUCCESS: Connected!");
    } catch (error) {
        console.error(">>> CONNECTION ERROR:", error);
        throw error;
    }

    return session;
}
