import { RealtimeAgent, RealtimeSession } from "@openai/agents/realtime";

/**
 * Creates and connects a new OpenAI Realtime Session using an Ephemeral Token 
 * generated by our secure SvelteKit backend route.
 * @param additionalInstructions Dynamic instructions to append to the system prompt
 */
export async function createCookingSession(additionalInstructions?: string) {
    console.log("Fetching Ephemeral Token from the server...");
    const response = await fetch('/api/realtime-session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ instructions: additionalInstructions })
    });
    
    if (!response.ok) {
        throw new Error('Failed to fetch ephemeral token from server');
    }
    
    const sessionData = await response.json();
    const ephemeralToken = sessionData.client_secret?.value;

    if (!ephemeralToken) {
        throw new Error('Server did not return a valid ephemeral token');
    }

    // 1. Define the Agent and its Function Calls (Tools)
    const agent = new RealtimeAgent({
        name: "Cooking Assistant",
        instructions: "You are a helpful culinary assistant guiding the user through cooking steps. You can create timers when the user asks.",
        tools: [
            {
                name: 'set_timer',
                description: 'Creates a cooking timer. Call this when the user needs to wait for something.',
                parameters: {
                    type: 'object',
                    properties: {
                        seconds: { type: 'number', description: 'Duration of the timer in seconds' },
                        reason: { type: 'string', description: 'What is cooking (e.g., "boil pasta")' }
                    },
                    required: ['seconds', 'reason'],
                    additionalProperties: false
                },
                execute: async (args: { seconds: number; reason: string }) => {
                    console.log(`[Function Called] Starting timer for ${args.seconds}s: ${args.reason}`);
                    
                    // TODO: Here you could dispatch a custom event to your Svelte components
                    // or update a global Svelte Store to show the timer on the UI!

                    // Return a result to the AI so it knows the function succeeded
                    return {
                        success: true,
                        message: `Timer set successfully for ${args.seconds} seconds.`
                    };
                }
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
            } as any            
        ]
    });

    // 3. Create the Session
    const session = new RealtimeSession(agent);

    // 3. Connect to the Realtime API automatically utilizing microphone & speaker natively
    // We pass the ephemeral key retrieved from our backend here securely!
    console.log("Connecting to OpenAI Realtime...");
    await session.connect({
        model: "gpt-4o-realtime-preview-2024-12-17",
        apiKey: ephemeralToken,
    });

    console.log("Connected successfully!");
    
    return session;
}
