import { RealtimeAgent, RealtimeSession } from "@openai/agents/realtime";

/**
 * Creates and connects a new OpenAI Realtime Session using an Ephemeral Token 
 * generated by our secure SvelteKit backend route.
 * @param additionalInstructions Dynamic instructions to append to the system prompt
 */
export async function createCookingSession() {
    console.log("Requesting microphone access...");
    try {
        await navigator.mediaDevices.getUserMedia({ audio: true });
    } catch {
        throw new Error("Microphone access denied. Please allow microphone permissions in your browser and try again.");
    }

    console.log("Fetching Ephemeral Token from the server...");
    const response = await fetch('/api/realtime-session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
    });
    
    if (!response.ok) {
        throw new Error('Failed to fetch ephemeral token from server');
    }
    
    const sessionData = await response.json();
    const ephemeralToken = sessionData.client_secret?.value;

    if (!ephemeralToken) {
        throw new Error('Server did not return a valid ephemeral token');
    }

    // 1. Define the Agent as per the official tutorial
    const agent = new RealtimeAgent({
        name: "Assistant",
        instructions: "You are a helpful assistant.",
    });

    // 2. Create the Session
    const session = new RealtimeSession(agent);

    // 3. Automatically connects your microphone and audio output
    // We use the ephemeralToken retrieved above as the <client-api-key>
    console.log("Connecting to OpenAI Realtime...");
    await session.connect({
        apiKey: ephemeralToken,
    });

    console.log("Connected successfully!");
    return session;
}
